[package]
name = "fc-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["David Valencia, davidalencia@ciencias.unam.mx"]
license = "MIT"
description = "Template para escribir una tesis para la facultad de ciencias."
categories = ["thesis"]
keywords = ["thesis", "tesis", "facultad", "ciencias"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"